Fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529531
http://gecko.lge.com:8000/Errors/Details/556939

FAILED: src/bufferencoder/CMakeFiles/buffer-encoder.dir/__/parser/serializer.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DPLATFORM_QEMUX86 -Dbuffer_encoder_EXPORTS -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot/usr/include/media-resource-calculator -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/build/src -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/. -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./base -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./cameraservice -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./log -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./util -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./cameraplayer -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./mediaencoderclient -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./bufferencoder -ITOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./camera-window-manager/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.35-r10  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.35-r10  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/build=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.35-r10  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/build=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.35-r10  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++14 -lrt -fPIC -MD -MT src/bufferencoder/CMakeFiles/buffer-encoder.dir/__/parser/serializer.cpp.o -MF src/bufferencoder/CMakeFiles/buffer-encoder.dir/__/parser/serializer.cpp.o.d -o src/bufferencoder/CMakeFiles/buffer-encoder.dir/__/parser/serializer.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/parser/serializer.cpp
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/parser/serializer.cpp:18:
TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./base/base.h:41:3: error: 'uint64_t' does not name a type
   41 |   uint64_t bit_rate;
      |   ^~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.35-r10/git/src/./base/base.h:22:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   21 | #include <vector>
  +++ |+#include <cstdint>
   22 |

FAILED: src/cameraplayer/CMakeFiles/cmp-player.dir/__/postProcess/PostProcessSolution.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DPTZ_ENABLED -Dcmp_player_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot/usr/include/media-resource-calculator -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/build/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/. -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./base -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./cameraservice -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./log -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./util -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./postProcess -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./cameraplayer -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./mediaencoderclient -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./bufferencoder -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/./camera-window-manager/include -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.36-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.36-r11  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/build=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.36-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/build=/usr/src/debug/g-camera-pipeline/1.0.0-13.gav.36-r11  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++14 -lrt -fPIC -MD -MT src/cameraplayer/CMakeFiles/cmp-player.dir/__/postProcess/PostProcessSolution.cpp.o -MF src/cameraplayer/CMakeFiles/cmp-player.dir/__/postProcess/PostProcessSolution.cpp.o.d -o src/cameraplayer/CMakeFiles/cmp-player.dir/__/postProcess/PostProcessSolution.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:19,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.cpp:17:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/IPostProcessSolution.hpp:31:31: error: 'uint8_t' has not been declared
   31 |     virtual bool pushMetaData(uint8_t *aMeta, int32_t aMetaLen) = 0;
      |                               ^~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/IPostProcessSolution.hpp:33:32: error: 'uint8_t' has not been declared
   33 |     virtual bool doPostProcess(uint8_t *aData, uint32_t aStrride,
      |                                ^~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/IPostProcessSolution.hpp:33:48: error: 'uint32_t' has not been declared
   33 |     virtual bool doPostProcess(uint8_t *aData, uint32_t aStrride,
      |                                                ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/IPostProcessSolution.hpp:34:32: error: 'uint32_t' has not been declared
   34 |                                uint32_t offsetUV)  = 0;
      |                                ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:35:31: error: 'uint8_t' has not been declared
   35 |     virtual bool pushMetaData(uint8_t *aMeta, int32_t aMetaLen) override;
      |                               ^~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:37:32: error: 'uint8_t' has not been declared
   37 |     virtual bool doPostProcess(uint8_t *aData, uint32_t aStrride,
      |                                ^~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:37:48: error: 'uint32_t' has not been declared
   37 |     virtual bool doPostProcess(uint8_t *aData, uint32_t aStrride,
      |                                                ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:38:32: error: 'uint32_t' has not been declared
   38 |                                uint32_t offsetUV) override;
      |                                ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:46:5: error: 'uint32_t' does not name a type
   46 |     uint32_t width_{0};
      |     ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:20:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   19 | #include "IPostProcessSolution.hpp"
  +++ |+#include <cstdint>
   20 |
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:47:5: error: 'uint32_t' does not name a type
   47 |     uint32_t height_{0};
      |     ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/g-camera-pipeline/1.0.0-13.gav.36-r11/git/src/postProcess/PostProcessSolution.hpp:47:5: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: Id709c53572b60d7c621fa695f0be0274ccf17760