Block webos-pro gcp build error
:Release Notes:
Define PACKAGECONFG[pro-ums] to fix webs-pro gcp build error caused by umediaserver.

:Detailed Notes:
| /data/home/Camera/shl.lee/pro/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-gav.50-r17/git/src/cameraservice/camera_service.cpp:40:13: error: 'UMS_CONNECTOR_ACG_BUS' was not declared in this scope; did you mean 'UMS_CONNECTOR_DUAL_BUS'?
|    40 |             UMS_CONNECTOR_ACG_BUS);
|       |             ^~~~~~~~~~~~~~~~~~~~~
|       |             UMS_CONNECTOR_DUAL_BUS

| /data/home/Camera/shl.lee/pro/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-gav.50-r17/git/src/resourcefacilitator/requestor.cpp:64:32: error: no matching function for call to 'uMediaServer::ResourceManagerClient::registerPipeline(const char [6], std::string&)'
|    64 |       umsRMC_->registerPipeline("media", appId_); // only rmc case
|       |       ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

| /data/home/Camera/shl.lee/pro/BUILD/work/qemux86_64-webos-linux/g-camera-pipeline/1.0.0-gav.50-r17/git/src/resourcefacilitator/requestor.cpp:260:12: error: 'using element_type = class uMediaServer::ResourceManagerClient' {aka 'class uMediaServer::ResourceManagerClient'} has no member named 'notifyPipelineStatus'
|   260 |   umsRMC_->notifyPipelineStatus(status);
|       |            ^~~~~~~~~~~~~~~~~~~~
:Testing Performed:
Local Build & Test : OK

:QA Notes:
N/A

:Issues Addressed:
[WRQ-10515] Unify camera architecture

Change-Id: I7b2857eba576b3bd37a485e110e646c2051cbd0f